title: Dario Arcos-Díaz, PhD
author: Dario Arcos-Díaz
#email: your-email@domain.com
description: >- # this means to ignore newlines until "show_exerpts:"
  Data Scientist and Neuroscientist with strong statistical 
  modeling and programming skills at the intersection between 
  machine learning and the natural sciences.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arcosdiaz.com" # the base hostname & protocol for your site, e.g. http://example.com

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
